import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Inject,
  Injectable,
  NotFoundException,
} from "@nestjs/common";
import { createHash } from "crypto";
import { Readable } from "stream";
import { plainToInstance } from "class-transformer";
import { validate } from "class-validator";
import type { PrismaClient } from "@st-michael/database";
import type { CurrentUserPayload } from "../auth/current-user.decorator";
import { LoyaltySearchDto } from "../loyalty-base/loyalty-base.dto";
import { LoyaltyBaseService } from "../loyalty-base/loyalty-base.service";
import {
  AGENCY_CALL_RESULTS,
  AssignmentBatchDto,
  BROKER_CALL_RESULTS,
  CampaignDetailQueryDto,
  CampaignListQueryDto,
  CorrectAttemptDto,
  CorrectEventDto,
  CreateAttemptDto,
  CreateCampaignDto,
  CreateEventDto,
  CreateGrantDto,
  CreateSavedViewDto,
  CreateTaskDto,
  EventListQueryDto,
  GrantListQueryDto,
  LoyaltyOptionalScopeDto,
  QueueQueryDto,
  ReplaceGrantProfileDto,
  SavedViewListQueryDto,
  TaskListQueryDto,
  UpdateSavedViewDto,
  UpdateTaskDto,
} from "./loyalty-workflow.dto";
import { LoyaltyPermissionService } from "./loyalty-permission.service";

type LoyaltyBase = "ANNA" | "OUR";
type LoyaltyEntity = "BROKER" | "AGENCY";
const OPEN_ASSIGNMENT_STATUSES = ["PENDING", "IN_PROGRESS"];
const MAX_FROZEN_CAMPAIGN_TARGETS = 20_000;
const MAX_CAMPAIGN_EXPORT_ROWS = 50_000;
const CAMPAIGN_ASSIGNMENT_STATUSES = [
  "PENDING",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
] as const;

function workflowCsvCell(value: unknown): string {
  let text = value === null || value === undefined ? "" : String(value);
  if (/^\s*[=+\-@]/.test(text) || /^[\t\r]/.test(text)) text = `'${text}`;
  return `"${text.replace(/"/g, '""')}"`;
}

function workflowCsvLine(values: unknown[]): string {
  return `${values.map(workflowCsvCell).join(",")}\r\n`;
}

@Injectable()
export class LoyaltyWorkflowService {
  constructor(
    @Inject("PrismaClient") private readonly prisma: PrismaClient,
    private readonly loyaltyBase: LoyaltyBaseService,
    private readonly permissions: LoyaltyPermissionService,
  ) {}

  private get db(): any {
    // Workflow models are generated by the accompanying additive migration.
    // Keeping the boundary here also makes unit tests independent of generation.
    return this.prisma as any;
  }

  effectivePermissions(user: CurrentUserPayload) {
    return this.permissions.effective(user);
  }

  async operators(user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    const rows = await this.db.broker.findMany({
      where: this.callOperatorWhere(),
      orderBy: { fullName: "asc" },
      select: { id: true, fullName: true, role: true },
    });
    return rows.map((row: any) => ({
      id: row.id,
      name: row.fullName,
      role: row.role,
    }));
  }

  async listCampaigns(query: CampaignListQueryDto, user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    const where: any = {};
    if (query.base) where.base = this.base(query.base);
    if (query.entityType) where.entityType = this.entity(query.entityType);
    if (query.status) where.status = query.status;
    const rows = await this.db.loyaltyCallCampaign.findMany({
      where,
      orderBy: { createdAt: "desc" },
      skip: (query.page - 1) * query.limit,
      take: query.limit,
      include: {
        _count: {
          select: {
            assignments: {
              where: { status: { in: OPEN_ASSIGNMENT_STATUSES } },
            },
          },
        },
      },
    });
    return rows.map((row: any) => this.campaignResponse(row));
  }

  async campaign(
    id: string,
    user: CurrentUserPayload,
    query: CampaignDetailQueryDto = new CampaignDetailQueryDto(),
  ) {
    await this.permissions.require(user, "READ_ALL");
    const page = query.page || 1;
    const limit = Math.min(query.limit || 100, 200);
    const row = await this.db.loyaltyCallCampaign.findUnique({
      where: { id },
      include: {
        createdBy: { select: { id: true, fullName: true, role: true } },
      },
    });
    if (!row) this.notFound();
    const [assignments, grouped] = await Promise.all([
      this.db.loyaltyCallAssignment.findMany({
        where: { campaignId: id },
        select: {
          id: true,
          status: true,
          version: true,
          annaPersonId: true,
          annaOrganizationId: true,
          ourBrokerId: true,
          ourAgencyId: true,
          assignedAt: true,
          completedAt: true,
          cancelledAt: true,
          assignedTo: { select: { id: true, fullName: true, role: true } },
          attempts: {
            orderBy: { occurredAt: "desc" },
            take: 1,
            select: { result: true, occurredAt: true },
          },
        },
        orderBy: [{ assignedAt: "asc" }, { id: "asc" }],
        skip: (page - 1) * limit,
        take: limit,
      }),
      this.db.loyaltyCallAssignment.groupBy({
        by: ["status"],
        where: { campaignId: id },
        _count: { _all: true },
      }),
    ]);
    const assignmentCounts = Object.fromEntries(
      CAMPAIGN_ASSIGNMENT_STATUSES.map((status) => [status, 0]),
    ) as Record<(typeof CAMPAIGN_ASSIGNMENT_STATUSES)[number], number>;
    for (const item of grouped) {
      if (item.status in assignmentCounts) {
        assignmentCounts[item.status as keyof typeof assignmentCounts] = Number(
          item._count?._all || 0,
        );
      }
    }
    const total = Object.values(assignmentCounts).reduce(
      (sum, value) => sum + value,
      0,
    );
    const remainingCount =
      assignmentCounts.PENDING + assignmentCounts.IN_PROGRESS;
    const frozenSelection = row.filterSnapshot?.selection;
    const frozenTargetIds = this.uniqueIds(row.filterSnapshot?.targetIds ?? []);
    const selection =
      frozenSelection?.mode === "IDS"
        ? {
            mode: "IDS",
            ids: frozenTargetIds.length
              ? frozenTargetIds
              : this.uniqueIds(frozenSelection.ids ?? []),
          }
        : frozenSelection?.mode === "FILTER"
          ? {
              mode: "FILTER",
              filterHash: row.filterHash,
              expectedCount: row.expectedCount,
              excludedIds: this.uniqueIds(frozenSelection.excludedIds ?? []),
            }
          : null;
    return {
      ...this.campaignResponse({
        ...row,
        _count: { assignments: remainingCount },
      }),
      version: row.version,
      filterHash: row.filterHash,
      selection,
      createdBy: this.operatorResponse(row.createdBy),
      assignments: assignments.map((assignment: any) =>
        this.campaignAssignmentResponse(assignment),
      ),
      assignmentCounts,
      assignmentPage: {
        page,
        pageSize: limit,
        total,
        totalPages: Math.max(1, Math.ceil(total / limit)),
      },
    };
  }

  async exportCampaign(id: string, user: CurrentUserPayload) {
    await this.permissions.requireAll(user, ["READ_ALL", "EXPORT"]);
    const campaign = await this.db.loyaltyCallCampaign.findUnique({
      where: { id },
      select: { id: true, name: true, status: true },
    });
    if (!campaign) this.notFound();
    const total = await this.db.loyaltyCallAssignment.count({
      where: { campaignId: id },
    });
    if (total > MAX_CAMPAIGN_EXPORT_ROWS) {
      throw new BadRequestException({
        message:
          "Campaign export exceeds the synchronous safety limit; archive or split the campaign",
        campaignId: id,
        total,
        maxRows: MAX_CAMPAIGN_EXPORT_ROWS,
      });
    }
    const assignments = await this.db.loyaltyCallAssignment.findMany({
      where: { campaignId: id },
      select: {
        id: true,
        status: true,
        annaPersonId: true,
        annaOrganizationId: true,
        ourBrokerId: true,
        ourAgencyId: true,
        assignedAt: true,
        completedAt: true,
        cancelledAt: true,
        assignedTo: { select: { id: true, fullName: true, role: true } },
        attempts: {
          orderBy: { occurredAt: "desc" },
          take: 1,
          select: { result: true, occurredAt: true },
        },
      },
      orderBy: [{ assignedAt: "asc" }, { id: "asc" }],
      take: MAX_CAMPAIGN_EXPORT_ROWS + 1,
    });
    if (assignments.length > MAX_CAMPAIGN_EXPORT_ROWS) {
      throw new BadRequestException({
        message:
          "Campaign export exceeds the synchronous safety limit; archive or split the campaign",
        campaignId: id,
        total: assignments.length,
        maxRows: MAX_CAMPAIGN_EXPORT_ROWS,
      });
    }
    const lines = [
      "\uFEFF",
      workflowCsvLine([
        "ID кампании",
        "Кампания",
        "Статус кампании",
        "ID записи",
        "Сотрудник",
        "Статус назначения",
        "Последний результат",
        "Назначено",
        "Последняя попытка",
        "Завершено",
        "Отменено",
      ]),
      ...assignments.map((assignment: any) => {
        const item = this.campaignAssignmentResponse(assignment);
        return workflowCsvLine([
          campaign.id,
          campaign.name,
          campaign.status,
          item.targetId,
          item.assignedTo?.name,
          item.status,
          item.lastResult,
          item.assignedAt?.toISOString?.() ?? item.assignedAt,
          item.lastAttemptAt?.toISOString?.() ?? item.lastAttemptAt,
          item.completedAt?.toISOString?.() ?? item.completedAt,
          item.cancelledAt?.toISOString?.() ?? item.cancelledAt,
        ]);
      }),
    ];
    const csv = Buffer.from(lines.join(""), "utf8");
    const sha256 = createHash("sha256").update(csv).digest("hex");
    await this.audit(
      this.db,
      user.id,
      "CAMPAIGN_CSV_EXPORTED",
      "CAMPAIGN",
      id,
      null,
      { rowCount: assignments.length, sha256 },
    );
    return {
      stream: Readable.from([csv]),
      fileName: `campaign-${id}.csv`,
      rowCount: assignments.length,
      sha256,
    };
  }

  async createCampaign(body: CreateCampaignDto, user: CurrentUserPayload) {
    await this.permissions.requireAll(user, ["READ_ALL", "CALL_ASSIGN"]);
    const base = this.base(body.base);
    const entityType = this.entity(body.entityType);
    const canonicalFilter = await this.validatedFilterSnapshot(
      body.filterSnapshot,
    );
    const resolved = await this.resolveCanonical(
      base,
      entityType,
      canonicalFilter,
    );
    if (
      resolved.filterHash !== body.filterHash ||
      (resolved.snapshotId ?? null) !== (body.snapshotId ?? null)
    ) {
      this.selectionDrift();
    }
    const resolvedIds = this.uniqueIds(resolved.ids);
    if (resolvedIds.length !== resolved.total) this.selectionDrift();
    const resolvedSet = new Set(resolvedIds);
    let selectedIds: string[];
    let frozenSelection: Record<string, unknown>;
    if (body.selection.mode === "IDS") {
      if (!body.selection.ids?.length || body.selection.excludedIds?.length) {
        throw new BadRequestException("Некорректный выбор записей");
      }
      selectedIds = this.uniqueIds(body.selection.ids);
      if (selectedIds.some((id) => !resolvedSet.has(id))) this.selectionDrift();
      if (
        body.selection.expectedCount !== undefined &&
        body.selection.expectedCount !== selectedIds.length
      )
        this.selectionDrift();
      frozenSelection = {
        mode: "IDS",
        expectedCount: selectedIds.length,
      };
    } else {
      if (
        body.selection.ids?.length ||
        body.selection.expectedCount === undefined ||
        (body.selection.filterHash &&
          body.selection.filterHash !== body.filterHash)
      ) {
        throw new BadRequestException("Некорректный выбор записей");
      }
      const excludedIds = this.uniqueIds(body.selection.excludedIds ?? []);
      if (excludedIds.some((id) => !resolvedSet.has(id))) this.selectionDrift();
      const excluded = new Set(excludedIds);
      selectedIds = resolvedIds.filter((id) => !excluded.has(id));
      if (body.selection.expectedCount !== selectedIds.length)
        this.selectionDrift();
      frozenSelection = {
        mode: "FILTER",
        expectedCount: selectedIds.length,
        excludedIds,
      };
    }
    if (!selectedIds.length) throw new BadRequestException("Не выбраны записи");
    if (selectedIds.length > MAX_FROZEN_CAMPAIGN_TARGETS) {
      throw new BadRequestException(
        `В одной кампании допускается не более ${MAX_FROZEN_CAMPAIGN_TARGETS} записей`,
      );
    }
    const persistedQuery = this.safeJson(
      this.withoutSensitiveSearch(canonicalFilter),
    );
    const filterSnapshot = this.safeJson(
      {
        version: 2,
        query: persistedQuery,
        targetIds: selectedIds,
        selection: frozenSelection,
        resolvedTotal: resolved.total,
        selectionDigest: this.idsDigest(selectedIds),
      },
      1_000_000,
    );
    const filterHash = resolved.filterHash;
    const snapshotId = resolved.snapshotId ?? null;
    return this.db.$transaction(async (tx: any) => {
      const created = await tx.loyaltyCallCampaign.create({
        data: {
          name: body.name,
          message: body.message,
          base,
          entityType,
          snapshotId,
          filterSnapshot,
          filterHash,
          expectedCount: selectedIds.length,
          createdById: user.id,
        },
      });
      await this.audit(
        tx,
        user.id,
        "CAMPAIGN_CREATED",
        "CAMPAIGN",
        created.id,
        null,
        {
          base,
          entityType,
          expectedCount: selectedIds.length,
          status: created.status,
        },
      );
      return {
        ...this.campaignResponse(created),
        version: created.version,
        filterHash,
      };
    });
  }

  async activateCampaign(
    id: string,
    expectedVersion: number,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "CALL_ASSIGN"]);
    return this.db.$transaction(async (tx: any) => {
      const campaign = await tx.loyaltyCallCampaign.findUnique({
        where: { id },
      });
      if (!campaign) this.notFound();
      if (campaign.status === "ACTIVE") {
        if (campaign.version !== expectedVersion) this.versionConflict();
        return {
          ...this.campaignResponse(campaign),
          version: campaign.version,
        };
      }
      if (campaign.status !== "DRAFT") this.stateConflict();
      const count = await tx.loyaltyCallAssignment.count({
        where: { campaignId: id },
      });
      if (!count)
        throw new BadRequestException("Нельзя активировать пустую кампанию");
      if (count !== campaign.expectedCount) this.selectionDrift();
      const changed = await tx.loyaltyCallCampaign.updateMany({
        where: { id, version: expectedVersion, status: "DRAFT" },
        data: {
          status: "ACTIVE",
          startedAt: new Date(),
          version: { increment: 1 },
        },
      });
      if (changed.count !== 1) this.versionConflict();
      const updated = await tx.loyaltyCallCampaign.findUnique({
        where: { id },
      });
      await this.audit(
        tx,
        user.id,
        "CAMPAIGN_ACTIVATED",
        "CAMPAIGN",
        id,
        { status: "DRAFT", version: expectedVersion },
        { status: "ACTIVE", version: updated.version },
      );
      return { ...this.campaignResponse(updated), version: updated.version };
    });
  }

  async archiveCampaign(
    id: string,
    expectedVersion: number,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "CALL_ASSIGN"]);
    return this.db.$transaction(async (tx: any) => {
      const campaign = await tx.loyaltyCallCampaign.findUnique({
        where: { id },
      });
      if (!campaign) this.notFound();
      if (campaign.status === "ARCHIVED") {
        if (campaign.version !== expectedVersion) this.versionConflict();
        return {
          ...this.campaignResponse(campaign),
          version: campaign.version,
        };
      }
      const changed = await tx.loyaltyCallCampaign.updateMany({
        where: { id, version: expectedVersion, status: { not: "ARCHIVED" } },
        data: {
          status: "ARCHIVED",
          archivedAt: new Date(),
          version: { increment: 1 },
        },
      });
      if (changed.count !== 1) this.versionConflict();
      const cancelled = await tx.loyaltyCallAssignment.updateMany({
        where: { campaignId: id, status: { in: OPEN_ASSIGNMENT_STATUSES } },
        data: {
          status: "CANCELLED",
          cancelledAt: new Date(),
          version: { increment: 1 },
        },
      });
      const updated = await tx.loyaltyCallCampaign.findUnique({
        where: { id },
      });
      await this.audit(
        tx,
        user.id,
        "CAMPAIGN_ARCHIVED",
        "CAMPAIGN",
        id,
        { status: campaign.status, version: campaign.version },
        {
          status: "ARCHIVED",
          version: updated.version,
          cancelledAssignments: cancelled.count,
        },
      );
      return { ...this.campaignResponse(updated), version: updated.version };
    });
  }

  async previewAssignments(
    id: string,
    body: AssignmentBatchDto,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "CALL_ASSIGN"]);
    const campaign = await this.assignmentCampaign(id, body.expectedVersion);
    await this.validAssignee(body.assigneeId);
    const ids = await this.selectionIds(campaign, body);
    await this.validateTargets(campaign, ids, true);
    const targetField = this.targetField(campaign.base, campaign.entityType);
    const existing = await this.db.loyaltyCallAssignment.count({
      where: { campaignId: id, [targetField]: { in: ids } },
    });
    return {
      campaignId: id,
      requestedCount: ids.length,
      assignableCount: ids.length - existing,
      duplicateCount: existing,
      assigneeId: body.assigneeId,
    };
  }

  async createAssignments(
    id: string,
    body: AssignmentBatchDto,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "CALL_ASSIGN"]);
    const campaign = await this.assignmentCampaign(id, body.expectedVersion);
    await this.validAssignee(body.assigneeId);
    const ids = await this.selectionIds(campaign, body);
    await this.validateTargets(campaign, ids, true);
    const targetField = this.targetField(campaign.base, campaign.entityType);
    return this.db.$transaction(async (tx: any) => {
      const current = await tx.loyaltyCallCampaign.findUnique({
        where: { id },
      });
      if (!current || !["DRAFT", "ACTIVE"].includes(current.status))
        this.stateConflict();
      if (
        body.expectedVersion !== undefined &&
        current.version !== body.expectedVersion
      ) {
        this.versionConflict();
      }
      let createdCount = 0;
      for (let index = 0; index < ids.length; index += 500) {
        const created = await tx.loyaltyCallAssignment.createMany({
          data: ids.slice(index, index + 500).map((targetId) => ({
            campaignId: id,
            [targetField]: targetId,
            assignedToId: body.assigneeId,
            assignedById: user.id,
          })),
          skipDuplicates: true,
        });
        createdCount += created.count;
      }
      const total = await tx.loyaltyCallAssignment.count({
        where: { campaignId: id },
      });
      if (total > campaign.expectedCount) this.selectionDrift();
      await this.audit(
        tx,
        user.id,
        "ASSIGNMENTS_CREATED",
        "CAMPAIGN",
        id,
        null,
        {
          createdCount,
          duplicateCount: ids.length - createdCount,
          totalCount: total,
        },
      );
      return {
        campaignId: id,
        requestedCount: ids.length,
        createdCount,
        duplicateCount: ids.length - createdCount,
        totalCount: total,
      };
    });
  }

  async queue(query: QueueQueryDto, user: CurrentUserPayload) {
    this.permissions.requireStaff(user);
    const requestedAssignee = query.assigneeId ?? user.id;
    if (user.role !== "ADMIN") {
      if (requestedAssignee === user.id) {
        await this.permissions.requireAny(user, [
          "READ_OWN_QUEUE",
          "CALL_EXECUTE",
        ]);
      } else {
        await this.permissions.require(user, "READ_ALL");
      }
    }
    const scopeWhere: any = { assignedToId: requestedAssignee };
    if (query.campaignId) scopeWhere.campaignId = query.campaignId;
    scopeWhere.campaign = query.status
      ? { status: { not: "ARCHIVED" } }
      : { status: "ACTIVE" };
    if (query.base) scopeWhere.campaign.base = this.base(query.base);
    if (query.entityType)
      scopeWhere.campaign.entityType = this.entity(query.entityType);
    const where = {
      ...scopeWhere,
      status: query.status ?? { in: OPEN_ASSIGNMENT_STATUSES },
    };
    const remainingWhere = {
      ...scopeWhere,
      status: { in: OPEN_ASSIGNMENT_STATUSES },
      campaign: { ...scopeWhere.campaign, status: "ACTIVE" },
    };
    const [rows, total, remaining] = await Promise.all([
      this.db.loyaltyCallAssignment.findMany({
        where,
        orderBy: { assignedAt: "asc" },
        skip: (query.page - 1) * query.limit,
        take: query.limit,
        select: {
          id: true,
          version: true,
          status: true,
          assignedAt: true,
          assignedTo: { select: { id: true, fullName: true, role: true } },
          annaPersonId: true,
          annaOrganizationId: true,
          ourBrokerId: true,
          ourAgencyId: true,
          ourBroker: {
            select: {
              fullName: true,
              phone: true,
              brokerAgencies: {
                where: { isPrimary: true, endedAt: null },
                take: 1,
                select: { agency: { select: { name: true } } },
              },
            },
          },
          ourAgency: { select: { name: true, phone: true, address: true } },
          campaign: {
            select: {
              id: true,
              name: true,
              message: true,
              base: true,
              entityType: true,
              snapshotId: true,
            },
          },
        },
      }),
      this.db.loyaltyCallAssignment.count({ where }),
      this.db.loyaltyCallAssignment.count({ where: remainingWhere }),
    ]);
    const sourceRecords = await this.queueSourceRecords(rows);
    const items = rows.map((row: any) =>
      this.queueResponse(row, sourceRecords),
    );
    return {
      items,
      total,
      remaining,
      page: query.page,
      pageSize: query.limit,
      totalPages: Math.ceil(total / query.limit),
    };
  }

  async createAttempt(
    assignmentId: string,
    body: CreateAttemptDto,
    user: CurrentUserPayload,
  ) {
    await this.permissions.require(user, "CALL_EXECUTE");
    if (body.assignmentId && body.assignmentId !== assignmentId) {
      throw new BadRequestException("Идентификатор назначения не совпадает");
    }
    const assignment = await this.attemptAssignment(assignmentId);
    this.requireAssignmentExecution(user, assignment.assignedToId);
    this.validateCallResult(assignment.campaign.entityType, body.result);
    this.validateAttemptComment(assignment.campaign.entityType, body);
    const existing = await this.db.loyaltyCallAttempt.findUnique({
      where: { submissionId: body.submissionId },
    });
    if (existing) {
      const response = this.idempotentAttempt(
        existing,
        assignmentId,
        user.id,
        body,
      );
      return {
        ...response,
        ...(await this.remainingAssignments(assignment)),
      };
    }
    if (assignment.campaign.status !== "ACTIVE") this.stateConflict();
    if (!OPEN_ASSIGNMENT_STATUSES.includes(assignment.status))
      this.stateConflict();
    try {
      return await this.db.$transaction(async (tx: any) => {
        const targetId = this.assignmentTargetId(assignment);
        if (!targetId) this.stateConflict();
        await this.validateTargets(assignment.campaign, [targetId], true, tx);
        const changed = await tx.loyaltyCallAssignment.updateMany({
          where: {
            id: assignmentId,
            version: body.expectedVersion,
            status: { in: OPEN_ASSIGNMENT_STATUSES },
          },
          data: {
            status: "COMPLETED",
            completedAt: new Date(),
            cancelledAt: null,
            version: { increment: 1 },
          },
        });
        if (changed.count !== 1) this.versionConflict();
        const attempt = await tx.loyaltyCallAttempt.create({
          data: {
            assignmentId,
            submissionId: body.submissionId,
            operatorId: user.id,
            result: body.result,
            comment: this.nullable(body.comment),
            nextStep: this.nullable(body.nextStep),
            nextActionAt: body.nextActionAt
              ? new Date(body.nextActionAt)
              : null,
          },
        });
        if (body.nextStep) {
          const followUp = await tx.loyaltyTask.create({
            data: {
              ...this.targetDataFromAssignment(assignment),
              assignmentId,
              callAttemptId: attempt.id,
              title: body.nextStep,
              dueAt: body.nextActionAt ? new Date(body.nextActionAt) : null,
              assignedToId: user.id,
              createdById: user.id,
            },
          });
          await this.audit(
            tx,
            user.id,
            "TASK_CREATED_FROM_CALL",
            "TASK",
            followUp.id,
            null,
            {
              assignmentId,
              status: followUp.status,
              hasDueAt: Boolean(body.nextActionAt),
            },
          );
        }
        await this.audit(
          tx,
          user.id,
          "CALL_ATTEMPT_RECORDED",
          "ASSIGNMENT",
          assignmentId,
          { status: assignment.status, version: body.expectedVersion },
          {
            status: "COMPLETED",
            version: body.expectedVersion + 1,
            result: body.result,
            hasComment: Boolean(body.comment),
            hasNextStep: Boolean(body.nextStep),
          },
        );
        const campaignRemaining = await tx.loyaltyCallAssignment.count({
          where: {
            campaignId: assignment.campaignId,
            status: { in: OPEN_ASSIGNMENT_STATUSES },
          },
        });
        const remaining = await tx.loyaltyCallAssignment.count({
          where: {
            campaignId: assignment.campaignId,
            assignedToId: assignment.assignedToId,
            status: { in: OPEN_ASSIGNMENT_STATUSES },
          },
        });
        if (campaignRemaining === 0) {
          const completed = await tx.loyaltyCallCampaign.updateMany({
            where: { id: assignment.campaignId, status: "ACTIVE" },
            data: {
              status: "COMPLETED",
              completedAt: new Date(),
              version: { increment: 1 },
            },
          });
          if (completed.count === 1) {
            await this.audit(
              tx,
              user.id,
              "CAMPAIGN_COMPLETED",
              "CAMPAIGN",
              assignment.campaignId,
              { status: "ACTIVE" },
              { status: "COMPLETED" },
            );
          }
        }
        return {
          ...attempt,
          idempotent: false,
          assignment: {
            id: assignmentId,
            status: "COMPLETED",
            version: body.expectedVersion + 1,
          },
          remaining,
          campaignRemaining,
        };
      });
    } catch (error) {
      if (this.prismaCode(error) === "P2002") {
        const raced = await this.db.loyaltyCallAttempt.findUnique({
          where: { submissionId: body.submissionId },
        });
        if (raced) {
          const response = this.idempotentAttempt(
            raced,
            assignmentId,
            user.id,
            body,
          );
          return {
            ...response,
            ...(await this.remainingAssignments(assignment)),
          };
        }
      }
      throw error;
    }
  }

  async listAttempts(assignmentId: string, user: CurrentUserPayload) {
    this.permissions.requireStaff(user);
    const assignment = await this.db.loyaltyCallAssignment.findUnique({
      where: { id: assignmentId },
      select: { id: true, assignedToId: true },
    });
    if (!assignment) this.notFound();
    if (user.role !== "ADMIN") {
      await this.permissions.require(
        user,
        assignment.assignedToId === user.id ? "CALL_EXECUTE" : "READ_ALL",
      );
    }
    const rows = await this.db.loyaltyCallAttempt.findMany({
      where: { assignmentId },
      orderBy: [{ occurredAt: "desc" }, { createdAt: "desc" }],
      take: 500,
      include: {
        operator: { select: { id: true, fullName: true, role: true } },
      },
    });
    return rows.map((row: any) => ({
      id: row.id,
      assignmentId: row.assignmentId,
      result: row.result,
      comment: row.comment ?? "",
      nextStep: row.nextStep ?? "",
      nextActionAt: row.nextActionAt,
      occurredAt: row.occurredAt,
      correctsAttemptId: row.correctsAttemptId,
      correctionReason: row.correctionReason ?? "",
      operator: this.operatorResponse(row.operator),
    }));
  }

  async correctAttempt(
    assignmentId: string,
    attemptId: string,
    body: CorrectAttemptDto,
    user: CurrentUserPayload,
  ) {
    await this.permissions.require(user, "CALL_EXECUTE");
    try {
      return await this.db.$transaction(
        async (tx: any) => {
          // All authorization and chain checks deliberately live in the same
          // serializable transaction as the append. This makes the predicate
          // read below participate in PostgreSQL SSI and prevents two callers
          // from creating sibling corrections for the same current leaf.
          const original = await tx.loyaltyCallAttempt.findUnique({
            where: { id: attemptId },
            include: { assignment: { include: { campaign: true } } },
          });
          if (!original || original.assignmentId !== assignmentId)
            this.notFound();
          this.requireAssignmentExecution(
            user,
            original.assignment.assignedToId,
          );
          this.validateCallResult(
            original.assignment.campaign.entityType,
            body.result,
          );
          this.validateAttemptComment(
            original.assignment.campaign.entityType,
            body,
          );

          const existing = await tx.loyaltyCallAttempt.findUnique({
            where: { submissionId: body.submissionId },
          });
          if (existing) {
            const compatible =
              existing.assignmentId === assignmentId &&
              existing.operatorId === user.id &&
              existing.correctsAttemptId === attemptId &&
              this.sameAttemptValues(existing, body) &&
              existing.correctionReason === body.correctionReason;
            if (!compatible) this.idempotencyConflict();
            return { ...existing, idempotent: true };
          }

          const descendants = await tx.loyaltyCallAttempt.findMany({
            where: { correctsAttemptId: attemptId },
            select: { id: true },
            take: 2,
          });
          if (descendants.length) this.stateConflict();

          const correction = await tx.loyaltyCallAttempt.create({
            data: {
              assignmentId,
              submissionId: body.submissionId,
              operatorId: user.id,
              result: body.result,
              comment: this.nullable(body.comment),
              nextStep: this.nullable(body.nextStep),
              nextActionAt: body.nextActionAt
                ? new Date(body.nextActionAt)
                : null,
              correctsAttemptId: attemptId,
              correctionReason: body.correctionReason,
            },
          });
          await this.audit(
            tx,
            user.id,
            "CALL_ATTEMPT_CORRECTED",
            "CALL_ATTEMPT",
            attemptId,
            null,
            { correctionId: correction.id, result: body.result },
          );
          return { ...correction, idempotent: false };
        },
        { isolationLevel: "Serializable" as any },
      );
    } catch (error) {
      if (this.prismaCode(error) === "P2002") {
        const raced = await this.db.loyaltyCallAttempt.findUnique({
          where: { submissionId: body.submissionId },
        });
        if (
          raced &&
          raced.assignmentId === assignmentId &&
          raced.operatorId === user.id &&
          raced.correctsAttemptId === attemptId &&
          this.sameAttemptValues(raced, body) &&
          raced.correctionReason === body.correctionReason
        ) {
          return { ...raced, idempotent: true };
        }
        this.idempotencyConflict();
      }
      if (this.prismaCode(error) === "P2034") this.stateConflict();
      throw error;
    }
  }

  async listTasks(query: TaskListQueryDto, user: CurrentUserPayload) {
    this.permissions.requireStaff(user);
    const where = this.scopedTargetWhere(query);
    if (user.role !== "ADMIN") {
      if (query.assignedToId && query.assignedToId !== user.id) {
        await this.permissions.require(user, "READ_ALL");
        where.assignedToId = query.assignedToId;
      } else {
        await this.permissions.requireAny(user, [
          "READ_OWN_QUEUE",
          "CALL_EXECUTE",
        ]);
        where.assignedToId = user.id;
      }
    } else if (query.assignedToId) {
      where.assignedToId = query.assignedToId;
    }
    if (query.status) where.status = query.status;
    const rows = await this.db.loyaltyTask.findMany({
      where,
      orderBy: [{ dueAt: "asc" }, { createdAt: "desc" }],
      skip: (query.page - 1) * query.limit,
      take: query.limit,
      include: {
        assignedTo: { select: { id: true, fullName: true, role: true } },
      },
    });
    return rows.map((row: any) => this.taskResponse(row));
  }

  async task(id: string, user: CurrentUserPayload) {
    this.permissions.requireStaff(user);
    const row = await this.db.loyaltyTask.findUnique({
      where: { id },
      include: {
        assignedTo: { select: { id: true, fullName: true, role: true } },
        createdBy: { select: { id: true, fullName: true, role: true } },
      },
    });
    if (!row) this.notFound();
    if (user.role !== "ADMIN") {
      if (row.assignedToId === user.id) {
        await this.permissions.requireAny(user, [
          "READ_OWN_QUEUE",
          "CALL_EXECUTE",
        ]);
      } else {
        await this.permissions.require(user, "READ_ALL");
      }
    }
    return this.taskResponse(row);
  }

  async createTask(body: CreateTaskDto, user: CurrentUserPayload) {
    this.permissions.requireStaff(user);
    const assigneeId = body.assignedToId ?? user.id;
    if (user.role !== "ADMIN") {
      await this.permissions.require(
        user,
        assigneeId === user.id ? "CALL_EXECUTE" : "ENTITY_EDIT",
      );
    }
    const base = this.base(body.base);
    const entityType = this.entity(body.entityType);
    await this.validateTargets(
      { base, entityType, snapshotId: await this.activeSnapshot(base) },
      [body.ownerId],
    );
    await this.validAssignee(assigneeId);
    if (body.assignmentId) {
      const assignment = await this.db.loyaltyCallAssignment.findUnique({
        where: { id: body.assignmentId },
      });
      if (!assignment || this.assignmentTargetId(assignment) !== body.ownerId)
        this.notFound();
    }
    return this.db.$transaction(async (tx: any) => {
      const created = await tx.loyaltyTask.create({
        data: {
          ...this.targetData(base, entityType, body.ownerId),
          assignmentId: body.assignmentId ?? null,
          title: body.title,
          description: this.nullable(body.description),
          dueAt: body.dueAt ? new Date(body.dueAt) : null,
          assignedToId: assigneeId,
          createdById: user.id,
        },
        include: {
          assignedTo: { select: { id: true, fullName: true, role: true } },
        },
      });
      await this.audit(tx, user.id, "TASK_CREATED", "TASK", created.id, null, {
        base,
        entityType,
        status: created.status,
        hasDueAt: Boolean(body.dueAt),
      });
      return this.taskResponse(created);
    });
  }

  async updateTask(id: string, body: UpdateTaskDto, user: CurrentUserPayload) {
    this.permissions.requireStaff(user);
    if (
      [
        body.title,
        body.description,
        body.status,
        body.assignedToId,
        body.dueAt,
      ].every((value) => value === undefined)
    ) {
      throw new BadRequestException("Не указаны изменения задачи");
    }
    const current = await this.db.loyaltyTask.findUnique({ where: { id } });
    if (!current) this.notFound();
    if (user.role !== "ADMIN") {
      const ownTask =
        current.assignedToId === user.id &&
        (body.assignedToId === undefined || body.assignedToId === user.id);
      await this.permissions.require(
        user,
        ownTask ? "CALL_EXECUTE" : "ENTITY_EDIT",
      );
    }
    if (body.assignedToId) await this.validAssignee(body.assignedToId);
    const data: any = { version: { increment: 1 } };
    if (body.title !== undefined) data.title = body.title;
    if (body.description !== undefined)
      data.description = this.nullable(body.description ?? undefined);
    if (body.assignedToId !== undefined) data.assignedToId = body.assignedToId;
    if (body.dueAt !== undefined)
      data.dueAt = body.dueAt ? new Date(body.dueAt) : null;
    if (body.status !== undefined) {
      data.status = body.status;
      data.completedAt = body.status === "COMPLETED" ? new Date() : null;
      data.cancelledAt = body.status === "CANCELLED" ? new Date() : null;
    }
    return this.db.$transaction(async (tx: any) => {
      const changed = await tx.loyaltyTask.updateMany({
        where: { id, version: body.expectedVersion },
        data,
      });
      if (changed.count !== 1) this.versionConflict();
      const updated = await tx.loyaltyTask.findUnique({
        where: { id },
        include: {
          assignedTo: { select: { id: true, fullName: true, role: true } },
        },
      });
      await this.audit(
        tx,
        user.id,
        "TASK_UPDATED",
        "TASK",
        id,
        { status: current.status, version: current.version },
        {
          status: updated.status,
          version: updated.version,
          hasDueAt: Boolean(updated.dueAt),
        },
      );
      return this.taskResponse(updated);
    });
  }

  async cancelTask(
    id: string,
    expectedVersion: number,
    user: CurrentUserPayload,
  ) {
    return this.updateTask(
      id,
      Object.assign(new UpdateTaskDto(), {
        expectedVersion,
        status: "CANCELLED",
      }),
      user,
    );
  }

  async listEvents(query: EventListQueryDto, user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    const where = this.scopedTargetWhere(query);
    if (query.type) where.type = query.type;
    if (!query.includeArchived) where.archivedAt = null;
    const rows = await this.db.loyaltyEngagementEvent.findMany({
      where,
      orderBy: [{ occurredAt: "desc" }, { createdAt: "desc" }],
      skip: (query.page - 1) * query.limit,
      take: query.limit,
      include: this.eventInclude(),
    });
    const states = await this.eventChainStates(this.db, rows);
    return rows.map((row: any) =>
      this.eventResponse(row, states.get(String(row.id))),
    );
  }

  async event(id: string, user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    const row = await this.db.loyaltyEngagementEvent.findUnique({
      where: { id },
      include: this.eventInclude(),
    });
    if (!row) this.notFound();
    const states = await this.eventChainStates(this.db, [row]);
    return this.eventResponse(row, states.get(String(row.id)));
  }

  async createEvent(body: CreateEventDto, user: CurrentUserPayload) {
    await this.permissions.requireAll(user, ["READ_ALL", "ENTITY_EDIT"]);
    const base = this.base(body.base);
    const entityType = this.entity(body.entityType);
    await this.validateTargets(
      { base, entityType, snapshotId: await this.activeSnapshot(base) },
      [body.ownerId],
    );
    this.validateEventDates(body.occurredAt, body.validUntil);
    return this.db.$transaction(async (tx: any) => {
      const created = await tx.loyaltyEngagementEvent.create({
        data: {
          ...this.targetData(base, entityType, body.ownerId),
          ...this.eventData(body),
          createdById: user.id,
        },
        include: this.eventInclude(),
      });
      await this.audit(
        tx,
        user.id,
        "EVENT_CREATED",
        "ENGAGEMENT_EVENT",
        created.id,
        null,
        {
          base,
          entityType,
          eventType: created.type,
          hasAmount: created.amount !== null,
        },
      );
      return this.eventResponse(created);
    });
  }

  async archiveEvent(
    id: string,
    expectedVersion: number,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "ENTITY_EDIT"]);
    return this.setEventArchived(id, expectedVersion, true, user);
  }

  async restoreEvent(
    id: string,
    expectedVersion: number,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "ENTITY_EDIT"]);
    return this.setEventArchived(id, expectedVersion, false, user);
  }

  private async setEventArchived(
    id: string,
    expectedVersion: number,
    archived: boolean,
    user: CurrentUserPayload,
  ) {
    try {
      return await this.db.$transaction(
        async (tx: any) => {
          const current = await tx.loyaltyEngagementEvent.findUnique({
            where: { id },
            include: this.eventInclude(),
          });
          if (!current) this.notFound();
          if (current.version !== expectedVersion) this.versionConflict();
          const states = await this.eventChainStates(tx, [current]);
          if (!states.get(String(current.id))?.current) this.stateConflict();
          if (Boolean(current.archivedAt) === archived) this.stateConflict();
          const archivedAt = archived ? new Date() : null;
          const changed = await tx.loyaltyEngagementEvent.updateMany({
            where: {
              id,
              version: expectedVersion,
              archivedAt: archived ? null : { not: null },
            },
            data: { archivedAt, version: { increment: 1 } },
          });
          if (changed.count !== 1) this.versionConflict();
          const updated = await tx.loyaltyEngagementEvent.findUnique({
            where: { id },
            include: this.eventInclude(),
          });
          if (!updated) this.notFound();
          await this.audit(
            tx,
            user.id,
            archived ? "EVENT_ARCHIVED" : "EVENT_RESTORED",
            "ENGAGEMENT_EVENT",
            id,
            { archived: !archived, version: current.version },
            { archived, version: updated.version },
          );
          return this.eventResponse(updated, {
            current: true,
            effective: !archived,
            superseded: false,
          });
        },
        { isolationLevel: "Serializable" as any },
      );
    } catch (error) {
      if (this.prismaCode(error) === "P2034") this.versionConflict();
      throw error;
    }
  }

  async correctEvent(
    id: string,
    body: CorrectEventDto,
    user: CurrentUserPayload,
  ) {
    await this.permissions.requireAll(user, ["READ_ALL", "ENTITY_EDIT"]);
    this.validateEventDates(body.occurredAt, body.validUntil);
    try {
      return await this.db.$transaction(
        async (tx: any) => {
          const original = await tx.loyaltyEngagementEvent.findUnique({
            where: { id },
            include: this.eventInclude(),
          });
          if (!original || original.archivedAt) this.notFound();
          const states = await this.eventChainStates(tx, [original]);
          if (!states.get(String(original.id))?.current) this.stateConflict();
          const correction = await tx.loyaltyEngagementEvent.create({
            data: {
              ...this.targetDataFromEvent(original),
              ...this.eventData(body),
              createdById: user.id,
              correctsEventId: id,
              correctionReason: body.correctionReason,
            },
            include: this.eventInclude(),
          });
          await this.audit(
            tx,
            user.id,
            "EVENT_CORRECTED",
            "ENGAGEMENT_EVENT",
            id,
            null,
            { correctionId: correction.id, eventType: correction.type },
          );
          return this.eventResponse(correction, {
            current: true,
            effective: true,
            superseded: false,
          });
        },
        { isolationLevel: "Serializable" as any },
      );
    } catch (error) {
      if (this.prismaCode(error) === "P2034") this.versionConflict();
      throw error;
    }
  }

  async listSavedViews(query: SavedViewListQueryDto, user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    const where: any = { OR: [{ ownerId: user.id }, { isShared: true }] };
    if (query.base) where.base = this.base(query.base);
    if (query.entityType) where.entityType = this.entity(query.entityType);
    const rows = await this.db.loyaltySavedView.findMany({
      where,
      orderBy: [{ isShared: "desc" }, { name: "asc" }],
      take: 200,
      include: { owner: { select: { id: true, fullName: true, role: true } } },
    });
    return rows.map((row: any) => this.savedViewResponse(row));
  }

  async createSavedView(body: CreateSavedViewDto, user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    if (body.isShared === true) {
      await this.permissions.require(user, "REFERENCE_MANAGE");
    }
    const base = this.base(body.base);
    const entityType = this.entity(body.entityType);
    const filters = this.safeJson(this.withoutSensitiveSearch(body.filters));
    try {
      return await this.db.$transaction(async (tx: any) => {
        const created = await tx.loyaltySavedView.create({
          data: {
            ownerId: user.id,
            name: body.name,
            base,
            entityType,
            filters,
            filterHash: this.hash(filters),
            isShared: body.isShared ?? false,
          },
          include: {
            owner: { select: { id: true, fullName: true, role: true } },
          },
        });
        await this.audit(
          tx,
          user.id,
          "SAVED_VIEW_CREATED",
          "SAVED_VIEW",
          created.id,
          null,
          { base, entityType, isShared: created.isShared },
        );
        return this.savedViewResponse(created);
      });
    } catch (error) {
      if (this.prismaCode(error) === "P2002") {
        throw new ConflictException(
          "Представление с таким именем уже существует",
        );
      }
      throw error;
    }
  }

  async updateSavedView(
    id: string,
    body: UpdateSavedViewDto,
    user: CurrentUserPayload,
  ) {
    await this.permissions.require(user, "READ_ALL");
    if (
      [body.name, body.filters, body.isShared].every(
        (value) => value === undefined,
      )
    ) {
      throw new BadRequestException("Не указаны изменения представления");
    }
    const current = await this.db.loyaltySavedView.findUnique({
      where: { id },
    });
    if (!current) this.notFound();
    if (user.role !== "ADMIN" && current.ownerId !== user.id)
      throw new ForbiddenException("Недостаточно прав");
    if (current.isShared || body.isShared === true) {
      await this.permissions.require(user, "REFERENCE_MANAGE");
    }
    const data: any = {};
    if (body.name !== undefined) data.name = body.name;
    if (body.isShared !== undefined) data.isShared = body.isShared;
    if (body.filters !== undefined) {
      data.filters = this.safeJson(this.withoutSensitiveSearch(body.filters));
      data.filterHash = this.hash(data.filters);
    }
    try {
      return await this.db.$transaction(async (tx: any) => {
        const updated = await tx.loyaltySavedView.update({
          where: { id },
          data,
          include: {
            owner: { select: { id: true, fullName: true, role: true } },
          },
        });
        await this.audit(
          tx,
          user.id,
          "SAVED_VIEW_UPDATED",
          "SAVED_VIEW",
          id,
          { isShared: current.isShared },
          { isShared: updated.isShared },
        );
        return this.savedViewResponse(updated);
      });
    } catch (error) {
      if (this.prismaCode(error) === "P2002") {
        throw new ConflictException(
          "Представление с таким именем уже существует",
        );
      }
      throw error;
    }
  }

  async deleteSavedView(id: string, user: CurrentUserPayload) {
    await this.permissions.require(user, "READ_ALL");
    const current = await this.db.loyaltySavedView.findUnique({
      where: { id },
    });
    if (!current) this.notFound();
    if (user.role !== "ADMIN" && current.ownerId !== user.id)
      throw new ForbiddenException("Недостаточно прав");
    if (current.isShared) {
      await this.permissions.require(user, "REFERENCE_MANAGE");
    }
    return this.db.$transaction(async (tx: any) => {
      await tx.loyaltySavedView.delete({ where: { id } });
      await this.audit(
        tx,
        user.id,
        "SAVED_VIEW_DELETED",
        "SAVED_VIEW",
        id,
        {
          base: current.base,
          entityType: current.entityType,
          isShared: current.isShared,
        },
        null,
      );
      return { id, deleted: true };
    });
  }

  async listGrants(query: GrantListQueryDto, user: CurrentUserPayload) {
    this.permissions.requireAdmin(user);
    const where: any = {};
    if (query.userId) where.userId = query.userId;
    if (!query.includeRevoked) where.revokedAt = null;
    return this.db.loyaltyUserGrant.findMany({
      where,
      orderBy: { grantedAt: "desc" },
      take: 500,
      include: {
        user: { select: { id: true, fullName: true, role: true } },
        grantedBy: { select: { id: true, fullName: true, role: true } },
      },
    });
  }

  async grantTargets(user: CurrentUserPayload) {
    this.permissions.requireAdmin(user);
    const rows = await this.db.broker.findMany({
      where: { role: "MANAGER", status: "ACTIVE", mergedIntoId: null },
      orderBy: { fullName: "asc" },
      select: { id: true, fullName: true, role: true },
    });
    return rows.map((row: any) => this.operatorResponse(row));
  }

  async replaceGrantProfile(
    body: ReplaceGrantProfileDto,
    user: CurrentUserPayload,
  ) {
    this.permissions.requireAdmin(user);
    const target = await this.db.broker.findFirst({
      where: {
        id: body.userId,
        role: "MANAGER",
        status: "ACTIVE",
        mergedIntoId: null,
      },
      select: { id: true },
    });
    if (!target) {
      throw new BadRequestException(
        "Профиль можно назначить только активному сотруднику",
      );
    }
    const permissions = Array.from(new Set(body.permissions)).sort();
    try {
      return await this.db.$transaction(
        async (tx: any) => {
          const active = await tx.loyaltyUserGrant.findMany({
            where: { userId: body.userId, revokedAt: null },
            select: { id: true, permission: true },
          });
          const before = active.map((item: any) => item.permission).sort();
          const expected = new Set(permissions);
          const revoked = active.filter(
            (item: any) => !expected.has(item.permission),
          );
          const now = new Date();
          if (revoked.length) {
            await tx.loyaltyUserGrant.updateMany({
              where: { id: { in: revoked.map((item: any) => item.id) } },
              data: { revokedAt: now },
            });
          }
          const current = new Set(
            active.map((item: any) => item.permission as string),
          );
          const granted: string[] = [];
          for (const permission of permissions) {
            if (current.has(permission)) continue;
            await tx.loyaltyUserGrant.create({
              data: {
                userId: body.userId,
                permission,
                grantedById: user.id,
              },
            });
            granted.push(permission);
          }
          await this.audit(
            tx,
            user.id,
            "GRANT_PROFILE_REPLACED",
            "USER_GRANT_PROFILE",
            body.userId,
            { permissions: before },
            { permissions },
          );
          return {
            userId: body.userId,
            permissions,
            granted,
            revoked: revoked.map((item: any) => item.permission),
          };
        },
        { isolationLevel: "Serializable" as any },
      );
    } catch (error) {
      if (this.prismaCode(error) === "P2034") this.stateConflict();
      throw error;
    }
  }

  async createGrant(body: CreateGrantDto, user: CurrentUserPayload) {
    this.permissions.requireAdmin(user);
    const target = await this.db.broker.findUnique({
      where: { id: body.userId },
      select: { id: true, role: true, status: true },
    });
    if (!target || target.role !== "MANAGER" || target.status !== "ACTIVE") {
      throw new BadRequestException(
        "Право можно выдать только активному сотруднику",
      );
    }
    const active = await this.db.loyaltyUserGrant.findFirst({
      where: {
        userId: body.userId,
        permission: body.permission,
        revokedAt: null,
      },
    });
    if (active) return { ...active, idempotent: true };
    try {
      return await this.db.$transaction(async (tx: any) => {
        const created = await tx.loyaltyUserGrant.create({
          data: {
            userId: body.userId,
            permission: body.permission,
            grantedById: user.id,
          },
        });
        await this.audit(
          tx,
          user.id,
          "GRANT_CREATED",
          "USER_GRANT",
          created.id,
          null,
          { userId: body.userId, permission: body.permission, active: true },
        );
        return { ...created, idempotent: false };
      });
    } catch (error) {
      if (this.prismaCode(error) === "P2002") {
        const raced = await this.db.loyaltyUserGrant.findFirst({
          where: {
            userId: body.userId,
            permission: body.permission,
            revokedAt: null,
          },
        });
        if (raced) return { ...raced, idempotent: true };
      }
      throw error;
    }
  }

  async revokeGrant(id: string, user: CurrentUserPayload) {
    this.permissions.requireAdmin(user);
    return this.db.$transaction(async (tx: any) => {
      const current = await tx.loyaltyUserGrant.findUnique({ where: { id } });
      if (!current) this.notFound();
      if (current.revokedAt) return { ...current, idempotent: true };
      const revokedAt = new Date();
      const changed = await tx.loyaltyUserGrant.updateMany({
        where: { id, revokedAt: null },
        data: { revokedAt },
      });
      if (changed.count !== 1) this.stateConflict();
      await this.audit(
        tx,
        user.id,
        "GRANT_REVOKED",
        "USER_GRANT",
        id,
        {
          userId: current.userId,
          permission: current.permission,
          active: true,
        },
        {
          userId: current.userId,
          permission: current.permission,
          active: false,
        },
      );
      return { ...current, revokedAt, idempotent: false };
    });
  }

  private requireAssignmentExecution(
    user: CurrentUserPayload,
    assigneeId: string,
  ): void {
    this.permissions.requireStaff(user);
    if (user.role === "ADMIN" || user.id === assigneeId) return;
    throw new ForbiddenException(
      "Call-center employees can record results only in their own queue",
    );
  }

  private base(value: string): LoyaltyBase {
    return value.toLowerCase() === "anna" ? "ANNA" : "OUR";
  }

  private entity(value: string): LoyaltyEntity {
    return value.toLowerCase().startsWith("agenc") ? "AGENCY" : "BROKER";
  }

  private responseBase(value: LoyaltyBase): "anna" | "ours" {
    return value === "ANNA" ? "anna" : "ours";
  }

  private responseEntity(value: LoyaltyEntity): "brokers" | "agencies" {
    return value === "BROKER" ? "brokers" : "agencies";
  }

  private campaignResponse(row: any) {
    const remainingCount =
      row._count?.assignments ??
      row.assignments?.filter((item: any) =>
        OPEN_ASSIGNMENT_STATUSES.includes(item.status),
      ).length ??
      0;
    return {
      id: row.id,
      name: row.name,
      message: row.message,
      base: this.responseBase(row.base),
      entityType: this.responseEntity(row.entityType),
      status: row.status,
      expectedCount: row.expectedCount,
      remainingCount,
      version: row.version,
      startedAt: row.startedAt,
      completedAt: row.completedAt,
      archivedAt: row.archivedAt,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };
  }

  private campaignAssignmentResponse(row: any) {
    return {
      id: row.id,
      status: row.status,
      version: row.version,
      targetId: this.assignmentTargetId(row),
      assignedTo: this.operatorResponse(row.assignedTo),
      assignedAt: row.assignedAt,
      completedAt: row.completedAt,
      cancelledAt: row.cancelledAt,
      lastResult: row.attempts?.[0]?.result ?? null,
      lastAttemptAt: row.attempts?.[0]?.occurredAt ?? null,
    };
  }

  private operatorResponse(row: any) {
    if (!row) return null;
    return { id: row.id, name: row.fullName, role: row.role };
  }

  private async assignmentCampaign(id: string, expectedVersion?: number) {
    const campaign = await this.db.loyaltyCallCampaign.findUnique({
      where: { id },
    });
    if (!campaign) this.notFound();
    if (!["DRAFT", "ACTIVE"].includes(campaign.status)) this.stateConflict();
    if (expectedVersion !== undefined && campaign.version !== expectedVersion)
      this.versionConflict();
    return campaign;
  }

  private async validAssignee(id: string) {
    const row = await this.db.broker.findFirst({
      where: this.callOperatorWhere(id),
      select: { id: true },
    });
    if (!row)
      throw new BadRequestException("Сотрудник недоступен для назначения");
  }

  private callOperatorWhere(id?: string) {
    return {
      ...(id ? { id } : {}),
      status: "ACTIVE",
      mergedIntoId: null,
      OR: [
        { role: "ADMIN" },
        {
          role: "MANAGER",
          loyaltyGrants: {
            some: { permission: "CALL_EXECUTE", revokedAt: null },
          },
        },
      ],
    };
  }

  private async selectionIds(
    campaign: any,
    body: AssignmentBatchDto,
  ): Promise<string[]> {
    if (!body.selection)
      throw new BadRequestException("Не задан выбор записей");
    const snapshot = campaign.filterSnapshot;
    const frozen = snapshot?.selection;
    if (snapshot?.version === 2) {
      const frozenIds = this.uniqueIds(snapshot.targetIds);
      if (
        !frozen ||
        typeof snapshot.selectionDigest !== "string" ||
        frozen.mode !== body.selection.mode ||
        frozenIds.length !== campaign.expectedCount ||
        this.idsDigest(frozenIds) !== snapshot.selectionDigest
      ) {
        this.selectionDrift();
      }
      if (frozen.mode === "IDS") {
        if (
          !body.selection.ids?.length ||
          body.selection.excludedIds?.length ||
          body.selection.filterHash ||
          !this.sameIds(frozenIds, this.uniqueIds(body.selection.ids))
        ) {
          this.selectionDrift();
        }
        return frozenIds;
      }
      if (
        body.selection.ids?.length ||
        !body.selection.filterHash ||
        body.selection.filterHash !== campaign.filterHash ||
        body.selection.expectedCount !== campaign.expectedCount ||
        !this.sameIds(
          this.uniqueIds(frozen.excludedIds ?? []),
          this.uniqueIds(body.selection.excludedIds ?? []),
        )
      ) {
        this.selectionDrift();
      }
      return frozenIds;
    }
    if (
      snapshot?.version !== 1 ||
      !snapshot?.query ||
      !frozen ||
      typeof snapshot.selectionDigest !== "string" ||
      frozen.mode !== body.selection.mode
    )
      this.selectionDrift();
    if (frozen.mode === "IDS") {
      if (
        !body.selection.ids?.length ||
        body.selection.excludedIds?.length ||
        body.selection.filterHash
      )
        this.selectionDrift();
      const frozenIds = this.uniqueIds(frozen.ids);
      const incomingIds = this.uniqueIds(body.selection.ids);
      if (
        !this.sameIds(frozenIds, incomingIds) ||
        frozenIds.length !== campaign.expectedCount ||
        this.idsDigest(frozenIds) !== snapshot.selectionDigest
      )
        this.selectionDrift();
      return frozenIds;
    }
    if (
      body.selection.ids?.length ||
      !body.selection.filterHash ||
      body.selection.filterHash !== campaign.filterHash ||
      body.selection.expectedCount !== campaign.expectedCount
    )
      this.selectionDrift();
    const frozenExclusions = this.uniqueIds(frozen.excludedIds ?? []);
    const incomingExclusions = this.uniqueIds(body.selection.excludedIds ?? []);
    if (!this.sameIds(frozenExclusions, incomingExclusions))
      this.selectionDrift();
    const resolved = await this.resolveCanonical(
      campaign.base,
      campaign.entityType,
      snapshot.query,
    );
    const resolvedIds = this.uniqueIds(resolved.ids);
    if (
      resolved.filterHash !== campaign.filterHash ||
      (resolved.snapshotId ?? null) !== (campaign.snapshotId ?? null) ||
      resolved.total !== snapshot.resolvedTotal ||
      resolvedIds.length !== resolved.total
    )
      this.selectionDrift();
    const excluded = new Set(frozenExclusions);
    const selectedIds = resolvedIds.filter((id) => !excluded.has(id));
    if (
      selectedIds.length !== campaign.expectedCount ||
      this.idsDigest(selectedIds) !== snapshot.selectionDigest
    )
      this.selectionDrift();
    return selectedIds;
  }

  private targetField(base: LoyaltyBase, entityType: LoyaltyEntity): string {
    if (base === "ANNA")
      return entityType === "BROKER" ? "annaPersonId" : "annaOrganizationId";
    return entityType === "BROKER" ? "ourBrokerId" : "ourAgencyId";
  }

  private targetData(base: LoyaltyBase, entityType: LoyaltyEntity, id: string) {
    return { [this.targetField(base, entityType)]: id };
  }

  private targetDataFromAssignment(row: any) {
    return {
      annaPersonId: row.annaPersonId,
      annaOrganizationId: row.annaOrganizationId,
      ourBrokerId: row.ourBrokerId,
      ourAgencyId: row.ourAgencyId,
    };
  }

  private targetDataFromEvent(row: any) {
    return {
      annaPersonId: row.annaPersonId,
      annaOrganizationId: row.annaOrganizationId,
      ourBrokerId: row.ourBrokerId,
      ourAgencyId: row.ourAgencyId,
    };
  }

  private assignmentTargetId(row: any): string | null {
    return (
      row.annaPersonId ??
      row.annaOrganizationId ??
      row.ourBrokerId ??
      row.ourAgencyId ??
      null
    );
  }

  private async activeSnapshot(
    base: LoyaltyBase,
    database: any = this.db,
  ): Promise<string | null> {
    if (base === "OUR") return null;
    const dataset = await database.loyaltyDataset.findFirst({
      where: {
        base: "ANNA",
        archivedAt: null,
        activeSnapshotId: { not: null },
      },
      orderBy: { updatedAt: "desc" },
      select: { activeSnapshotId: true },
    });
    if (!dataset?.activeSnapshotId)
      throw new ConflictException("Активный снимок базы недоступен");
    return dataset.activeSnapshotId;
  }

  private async validateTargets(
    campaign: any,
    ids: string[],
    driftIsConflict = false,
    database: any = this.db,
  ): Promise<void> {
    if (!ids.length) throw new BadRequestException("Не выбраны записи");
    let found: Array<{ id: string }> = [];
    if (campaign.base === "ANNA") {
      const snapshotId =
        campaign.snapshotId ?? (await this.activeSnapshot("ANNA", database));
      const field =
        campaign.entityType === "BROKER" ? "personId" : "organizationId";
      const records = await database.loyaltySourceRecord.findMany({
        where: {
          snapshotId,
          entityType: campaign.entityType,
          sourceArchivedAt: null,
          [field]: { in: ids },
          ...(campaign.entityType === "BROKER"
            ? { person: { is: { archivedAt: null } } }
            : { organization: { is: { archivedAt: null } } }),
        },
        distinct: [field],
        select: { [field]: true },
      });
      found = records
        .map((row: any) => ({ id: row[field] }))
        .filter((row: any) => row.id);
      const foundIds = new Set(found.map((row) => row.id));
      const missingIds = ids.filter((id) => !foundIds.has(id));
      if (missingIds.length) {
        const relationName =
          campaign.entityType === "BROKER" ? "person" : "organization";
        const overlays = await database.loyaltyManualEntity.findMany({
          where: {
            entityType: campaign.entityType,
            archivedAt: null,
            dataset: { snapshots: { some: { id: snapshotId } } },
            [field]: { in: missingIds },
            [relationName]: { is: { archivedAt: null } },
          },
          select: { [field]: true },
        });
        found.push(
          ...overlays
            .map((row: any) => ({ id: row[field] }))
            .filter((row: any) => row.id),
        );
      }
    } else if (campaign.entityType === "BROKER") {
      found = await database.broker.findMany({
        where: { id: { in: ids }, mergedIntoId: null },
        select: { id: true },
      });
    } else {
      found = await database.agency.findMany({
        where: { id: { in: ids } },
        select: { id: true },
      });
    }
    if (new Set(found.map((row) => row.id)).size !== ids.length) {
      if (driftIsConflict) this.selectionDrift();
      throw new BadRequestException("Выбор содержит недоступные записи");
    }
  }

  private async attemptAssignment(id: string) {
    const row = await this.db.loyaltyCallAssignment.findUnique({
      where: { id },
      include: { campaign: true },
    });
    if (!row) this.notFound();
    return row;
  }

  private validateCallResult(entityType: LoyaltyEntity, value: string): void {
    const catalog: readonly string[] =
      entityType === "BROKER" ? BROKER_CALL_RESULTS : AGENCY_CALL_RESULTS;
    if (!catalog.includes(value)) {
      throw new BadRequestException("Результат звонка не подходит типу записи");
    }
  }

  private validateAttemptComment(
    entityType: LoyaltyEntity,
    body: CreateAttemptDto | CorrectAttemptDto,
  ): void {
    if (entityType !== "AGENCY" || String(body.comment || "").trim()) return;
    throw new BadRequestException(
      body.result === "AGREEMENTS_EXIST"
        ? "Укажите содержание договорённости с агентством"
        : "Для звонка агентству обязателен краткий комментарий",
    );
  }

  private async remainingAssignments(assignment: {
    campaignId: string;
    assignedToId: string;
  }) {
    const [remaining, campaignRemaining] = await Promise.all([
      this.db.loyaltyCallAssignment.count({
        where: {
          campaignId: assignment.campaignId,
          assignedToId: assignment.assignedToId,
          status: { in: OPEN_ASSIGNMENT_STATUSES },
        },
      }),
      this.db.loyaltyCallAssignment.count({
        where: {
          campaignId: assignment.campaignId,
          status: { in: OPEN_ASSIGNMENT_STATUSES },
        },
      }),
    ]);
    return { remaining, campaignRemaining };
  }

  private idempotentAttempt(
    existing: any,
    assignmentId: string,
    operatorId: string,
    body: CreateAttemptDto,
  ) {
    if (
      existing.assignmentId !== assignmentId ||
      existing.operatorId !== operatorId ||
      existing.correctsAttemptId !== null ||
      !this.sameAttemptValues(existing, body)
    ) {
      this.idempotencyConflict();
    }
    return { ...existing, idempotent: true };
  }

  private sameAttemptValues(
    existing: any,
    body: CreateAttemptDto | CorrectAttemptDto,
  ): boolean {
    const existingNext = existing.nextActionAt
      ? new Date(existing.nextActionAt).toISOString()
      : null;
    const bodyNext = body.nextActionAt
      ? new Date(body.nextActionAt).toISOString()
      : null;
    return (
      existing.result === body.result &&
      (existing.comment ?? null) === this.nullable(body.comment) &&
      (existing.nextStep ?? null) === this.nullable(body.nextStep) &&
      existingNext === bodyNext
    );
  }

  private async queueSourceRecords(rows: any[]): Promise<Map<string, any>> {
    const ors = rows
      .filter((row) => row.campaign.base === "ANNA" && row.campaign.snapshotId)
      .map((row) =>
        row.annaPersonId
          ? {
              snapshotId: row.campaign.snapshotId,
              personId: row.annaPersonId,
              person: { is: { archivedAt: null } },
            }
          : {
              snapshotId: row.campaign.snapshotId,
              organizationId: row.annaOrganizationId,
              organization: { is: { archivedAt: null } },
            },
      );
    if (!ors.length) return new Map();
    const records = await this.db.loyaltySourceRecord.findMany({
      where: { OR: ors, sourceArchivedAt: null },
      select: {
        snapshotId: true,
        personId: true,
        organizationId: true,
        displayName: true,
        city: true,
        attributes: true,
        contactPoints: {
          where: { type: "PHONE" },
          orderBy: [{ isPrimary: "desc" }, { createdAt: "asc" }],
          select: {
            value: true,
            normalizedValue: true,
            isPrimary: true,
            createdAt: true,
          },
        },
        person: {
          select: {
            contactOverrides: {
              where: { type: "PHONE", archivedAt: null },
              orderBy: [{ isPrimary: "desc" }, { createdAt: "asc" }],
              select: {
                value: true,
                normalizedValue: true,
                isPrimary: true,
                createdAt: true,
              },
            },
          },
        },
        organization: {
          select: {
            contactOverrides: {
              where: { type: "PHONE", archivedAt: null },
              orderBy: [{ isPrimary: "desc" }, { createdAt: "asc" }],
              select: {
                value: true,
                normalizedValue: true,
                isPrimary: true,
                createdAt: true,
              },
            },
          },
        },
      },
    });
    for (const record of records) {
      const overrides =
        record.person?.contactOverrides ??
        record.organization?.contactOverrides ??
        [];
      record.contactPoints = this.queuePhoneContacts(
        record.contactPoints,
        overrides,
      );
    }
    const result = new Map<string, any>(
      records.map((record: any) => [
        `${record.snapshotId}:${record.personId ?? record.organizationId}`,
        record,
      ]),
    );
    const missingRows = rows.filter((row) => {
      if (row.campaign.base !== "ANNA" || !row.campaign.snapshotId)
        return false;
      const id = row.annaPersonId ?? row.annaOrganizationId;
      return !result.has(`${row.campaign.snapshotId}:${id}`);
    });
    for (const row of missingRows) {
      const targetId = row.annaPersonId ?? row.annaOrganizationId;
      const field = row.annaPersonId ? "personId" : "organizationId";
      const relationName = row.annaPersonId ? "person" : "organization";
      const overlay = await this.db.loyaltyManualEntity.findFirst({
        where: {
          archivedAt: null,
          dataset: {
            snapshots: { some: { id: row.campaign.snapshotId } },
          },
          [field]: targetId,
          [relationName]: { is: { archivedAt: null } },
        },
        select: {
          displayName: true,
          city: true,
          contactPoints: true,
          attributes: true,
          [relationName]: {
            select: {
              contactOverrides: {
                where: { type: "PHONE", archivedAt: null },
                orderBy: [{ isPrimary: "desc" }, { createdAt: "asc" }],
                select: {
                  value: true,
                  normalizedValue: true,
                  isPrimary: true,
                  createdAt: true,
                },
              },
            },
          },
        },
      });
      if (overlay) {
        overlay.contactPoints = this.queuePhoneContacts(
          overlay.contactPoints,
          overlay[relationName]?.contactOverrides ?? [],
        );
        result.set(`${row.campaign.snapshotId}:${targetId}`, overlay);
      }
    }
    return result;
  }

  private queuePhoneContacts(source: unknown, overrides: unknown): any[] {
    const rows: Array<any & { manualOverride: boolean }> = [
      ...(Array.isArray(source)
        ? source.map((point) => ({ ...point, manualOverride: false }))
        : []),
      ...(Array.isArray(overrides)
        ? overrides.map((point) => ({ ...point, manualOverride: true }))
        : []),
    ];
    const byValue = new Map<string, (typeof rows)[number]>();
    for (const point of rows) {
      const key = String(
        point.normalizedValue || point.normalized || point.value || "",
      );
      if (!key) continue;
      const existing = byValue.get(key);
      if (!existing || point.manualOverride) byValue.set(key, point);
    }
    return [...byValue.values()].sort(
      (left, right) =>
        Number(Boolean(right.isPrimary)) - Number(Boolean(left.isPrimary)) ||
        Number(right.manualOverride) - Number(left.manualOverride) ||
        new Date(left.createdAt || 0).getTime() -
          new Date(right.createdAt || 0).getTime(),
    );
  }

  private queueResponse(row: any, records: Map<string, any>) {
    const targetId = this.assignmentTargetId(row);
    const anna =
      row.campaign.base === "ANNA"
        ? records.get(`${row.campaign.snapshotId}:${targetId}`)
        : null;
    const targetName =
      anna?.displayName ??
      row.ourBroker?.fullName ??
      row.ourAgency?.name ??
      "Без названия";
    const phone =
      anna?.contactPoints?.[0]?.value ??
      row.ourBroker?.phone ??
      row.ourAgency?.phone ??
      "";
    const company = row.ourBroker?.brokerAgencies?.[0]?.agency?.name ?? "";
    const location = anna?.city ?? row.ourAgency?.address ?? "";
    return {
      id: row.id,
      version: row.version,
      status: row.status,
      targetId,
      targetName,
      entityType: this.responseEntity(row.campaign.entityType),
      base: this.responseBase(row.campaign.base),
      phone,
      company,
      context: location,
      campaign: {
        id: row.campaign.id,
        name: row.campaign.name,
        message: row.campaign.message,
      },
      assignedTo: this.operatorResponse(row.assignedTo),
      assignedAt: row.assignedAt,
    };
  }

  private scopedTargetWhere(
    query: LoyaltyOptionalScopeDto & { ownerId?: string },
  ): any {
    if (Boolean(query.base) !== Boolean(query.entityType)) {
      throw new BadRequestException("База и тип записи задаются вместе");
    }
    if (!query.base) {
      if (query.ownerId)
        throw new BadRequestException("Для записи нужна база и тип");
      return {};
    }
    const base = this.base(query.base);
    const entityType = this.entity(query.entityType!);
    return query.ownerId
      ? this.targetData(base, entityType, query.ownerId)
      : {
          [this.targetField(base, entityType)]: { not: null },
        };
  }

  private targetScope(row: any): {
    base: LoyaltyBase;
    entityType: LoyaltyEntity;
    ownerId: string;
  } {
    if (row.annaPersonId)
      return { base: "ANNA", entityType: "BROKER", ownerId: row.annaPersonId };
    if (row.annaOrganizationId)
      return {
        base: "ANNA",
        entityType: "AGENCY",
        ownerId: row.annaOrganizationId,
      };
    if (row.ourBrokerId)
      return { base: "OUR", entityType: "BROKER", ownerId: row.ourBrokerId };
    return { base: "OUR", entityType: "AGENCY", ownerId: row.ourAgencyId };
  }

  private taskResponse(row: any) {
    const scope = this.targetScope(row);
    return {
      id: row.id,
      version: row.version,
      base: this.responseBase(scope.base),
      entityType: this.responseEntity(scope.entityType),
      ownerId: scope.ownerId,
      title: row.title,
      description: row.description ?? "",
      dueAt: row.dueAt ?? "",
      status: row.status,
      assignedTo: this.operatorResponse(row.assignedTo),
      createdBy: this.operatorResponse(row.createdBy),
      assignmentId: row.assignmentId,
      callAttemptId: row.callAttemptId,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };
  }

  private validateEventDates(occurredAt: string, validUntil?: string): void {
    if (
      validUntil &&
      new Date(validUntil).getTime() < new Date(occurredAt).getTime()
    ) {
      throw new BadRequestException(
        "Срок действия не может быть раньше даты события",
      );
    }
  }

  private eventData(body: CreateEventDto | CorrectEventDto): any {
    return {
      type: body.type,
      occurredAt: new Date(body.occurredAt),
      comment: this.nullable(body.comment),
      amount: body.amount ?? null,
      value: this.nullable(body.value),
      validUntil: body.validUntil ? new Date(body.validUntil) : null,
      attachmentUrl: this.nullable(body.attachmentUrl),
      basisUrl: this.nullable(body.basisUrl),
    };
  }

  private eventInclude() {
    return {
      createdBy: { select: { id: true, fullName: true, role: true } },
      attachments: {
        where: { archivedAt: null },
        orderBy: [{ createdAt: "asc" as const }, { id: "asc" as const }],
        select: {
          id: true,
          fileName: true,
          mimeType: true,
          size: true,
          sha256: true,
          version: true,
          createdAt: true,
        },
      },
    };
  }

  private async eventChainStates(
    database: any,
    seeds: any[],
  ): Promise<
    Map<string, { current: boolean; effective: boolean; superseded: boolean }>
  > {
    const select = {
      id: true,
      correctsEventId: true,
      archivedAt: true,
      createdAt: true,
    };
    const nodes = new Map<string, any>();
    for (const seed of seeds) {
      if (seed?.id) nodes.set(String(seed.id), seed);
    }
    if (!nodes.size) return new Map();

    let frontier = [...nodes.values()]
      .map((row) => row.correctsEventId && String(row.correctsEventId))
      .filter((id): id is string => Boolean(id) && !nodes.has(id));
    for (let round = 0; frontier.length && round < 100; round += 1) {
      const wanted = new Set(frontier);
      const fetchedRaw = await database.loyaltyEngagementEvent.findMany({
        where: { id: { in: [...wanted] } },
        select,
      });
      const fetched = (Array.isArray(fetchedRaw) ? fetchedRaw : []).filter(
        (row: any) => wanted.has(String(row?.id || "")),
      );
      if (!fetched.length) break;
      for (const row of fetched) nodes.set(String(row.id), row);
      if (nodes.size > 10000) this.stateConflict();
      frontier = fetched
        .map((row: any) =>
          row.correctsEventId ? String(row.correctsEventId) : null,
        )
        .filter(
          (id: string | null): id is string => Boolean(id) && !nodes.has(id!),
        );
    }
    if (frontier.length) this.stateConflict();

    const rootId = (row: any): string => {
      let current = row;
      const seen = new Set<string>();
      while (
        current?.correctsEventId &&
        nodes.has(String(current.correctsEventId)) &&
        !seen.has(String(current.correctsEventId))
      ) {
        seen.add(String(current.id));
        current = nodes.get(String(current.correctsEventId));
      }
      return String(current?.id || row.id);
    };
    const roots = new Set(
      seeds.filter((row) => row?.id).map((row) => rootId(row)),
    );
    let parentFrontier = [...roots];
    const expanded = new Set<string>();
    for (let round = 0; parentFrontier.length && round < 100; round += 1) {
      const parentIds = new Set(
        parentFrontier.filter((id) => !expanded.has(id)),
      );
      if (!parentIds.size) break;
      for (const id of parentIds) expanded.add(id);
      const childrenRaw = await database.loyaltyEngagementEvent.findMany({
        where: { correctsEventId: { in: [...parentIds] } },
        select,
      });
      const children = (Array.isArray(childrenRaw) ? childrenRaw : []).filter(
        (row: any) => parentIds.has(String(row?.correctsEventId || "")),
      );
      parentFrontier = [];
      for (const row of children) {
        const id = String(row.id);
        nodes.set(id, row);
        if (!expanded.has(id)) parentFrontier.push(id);
      }
      if (nodes.size > 10000) this.stateConflict();
    }
    if (parentFrontier.length) this.stateConflict();

    const chains = new Map<string, any[]>();
    for (const row of nodes.values()) {
      const root = rootId(row);
      if (!roots.has(root)) continue;
      const chain = chains.get(root) || [];
      chain.push(row);
      chains.set(root, chain);
    }
    const states = new Map<
      string,
      { current: boolean; effective: boolean; superseded: boolean }
    >();
    for (const chain of chains.values()) {
      const ordered = [...chain].sort((left, right) =>
        this.eventChainSortKey(left).localeCompare(
          this.eventChainSortKey(right),
        ),
      );
      const currentId = String(ordered[ordered.length - 1].id);
      const currentArchived = Boolean(ordered[ordered.length - 1].archivedAt);
      for (const row of ordered) {
        const current = String(row.id) === currentId;
        states.set(String(row.id), {
          current,
          effective: current && !currentArchived,
          superseded: !current,
        });
      }
    }
    return states;
  }

  private eventChainSortKey(row: any): string {
    const parsed = row?.createdAt ? new Date(row.createdAt) : null;
    const createdAt =
      parsed && Number.isFinite(parsed.getTime()) ? parsed.toISOString() : "";
    return `${createdAt}\u0000${String(row?.id || "")}`;
  }

  private eventResponse(
    row: any,
    state: { current: boolean; effective: boolean; superseded: boolean } = {
      current: true,
      effective: !row.archivedAt,
      superseded: false,
    },
  ) {
    const scope = this.targetScope(row);
    return {
      id: row.id,
      version: row.version,
      base: this.responseBase(scope.base),
      entityType: this.responseEntity(scope.entityType),
      ownerId: scope.ownerId,
      type: row.type,
      occurredAt: row.occurredAt,
      employee: row.createdBy?.fullName ?? "",
      createdBy: this.operatorResponse(row.createdBy),
      comment: row.comment ?? "",
      amount:
        row.amount === null || row.amount === undefined
          ? null
          : String(row.amount),
      value: row.value ?? "",
      validUntil: row.validUntil ?? "",
      attachmentUrl: row.attachmentUrl ?? "",
      basisUrl: row.basisUrl ?? "",
      correctsEventId: row.correctsEventId,
      correctionReason: row.correctionReason ?? "",
      archivedAt: row.archivedAt,
      attachments: (Array.isArray(row.attachments) ? row.attachments : []).map(
        (attachment: any) => ({
          id: attachment.id,
          fileName: attachment.fileName,
          mimeType: attachment.mimeType,
          size: Number(attachment.size),
          sha256: attachment.sha256,
          version: attachment.version,
          createdAt: attachment.createdAt,
          downloadUrl: `/api/loyalty-attachments/${encodeURIComponent(
            attachment.id,
          )}`,
        }),
      ),
      current: state.current,
      effective: state.effective,
      superseded: state.superseded,
      createdAt: row.createdAt,
    };
  }

  private savedViewResponse(row: any) {
    return {
      id: row.id,
      name: row.name,
      base: this.responseBase(row.base),
      entityType: this.responseEntity(row.entityType),
      filters: row.filters,
      filterHash: row.filterHash,
      isShared: row.isShared,
      owner: this.operatorResponse(row.owner),
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };
  }

  private async resolveCanonical(
    base: LoyaltyBase,
    entityType: LoyaltyEntity,
    filterSnapshot: Record<string, unknown>,
  ): Promise<{
    ids: string[];
    total: number;
    filterHash: string;
    snapshotId: string | null;
  }> {
    try {
      return await this.loyaltyBase.resolveSelection(
        this.responseBase(base),
        entityType as any,
        filterSnapshot as any,
      );
    } catch (error) {
      if (error instanceof BadRequestException) {
        throw new BadRequestException("Не удалось проверить снимок фильтра");
      }
      throw error;
    }
  }

  private async validatedFilterSnapshot(value: Record<string, unknown>) {
    const instance = plainToInstance(LoyaltySearchDto, value);
    const errors = await validate(instance, {
      whitelist: true,
      forbidNonWhitelisted: true,
      validationError: { target: false, value: false },
    });
    if (errors.length)
      throw new BadRequestException("Некорректный снимок фильтра");
    return this.safeJson(instance);
  }

  private withoutSensitiveSearch(value: unknown): unknown {
    if (Array.isArray(value)) {
      return value.map((entry) => this.withoutSensitiveSearch(entry));
    }
    if (!value || typeof value !== "object") return value;
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .filter(([key]) => key.toLowerCase() !== "search")
        .map(([key, entry]) => [key, this.withoutSensitiveSearch(entry)]),
    );
  }

  private uniqueIds(values: unknown): string[] {
    if (
      !Array.isArray(values) ||
      values.length > 100_000 ||
      !values.every((value) => typeof value === "string" && value.length <= 100)
    ) {
      throw new BadRequestException("Некорректный выбор записей");
    }
    return Array.from(new Set(values as string[]));
  }

  private sameIds(left: string[], right: string[]): boolean {
    if (left.length !== right.length) return false;
    const rightSet = new Set(right);
    return left.every((id) => rightSet.has(id));
  }

  private idsDigest(ids: string[]): string {
    return createHash("sha256")
      .update([...ids].sort().join("\n"))
      .digest("hex");
  }

  private safeJson(value: unknown, maxBytes = 100_000): any {
    let serialized: string;
    try {
      serialized = this.stableStringify(value);
    } catch {
      throw new BadRequestException("Некорректный набор фильтров");
    }
    if (Buffer.byteLength(serialized, "utf8") > maxBytes) {
      throw new BadRequestException("Набор фильтров слишком большой");
    }
    return JSON.parse(serialized);
  }

  private stableStringify(value: unknown): string {
    const seen = new WeakSet<object>();
    const normalize = (item: any, depth: number): any => {
      if (depth > 20) throw new Error("depth");
      if (item === null || typeof item !== "object") return item;
      if (seen.has(item)) throw new Error("cycle");
      seen.add(item);
      if (Array.isArray(item))
        return item.map((entry) => normalize(entry, depth + 1));
      const result: Record<string, unknown> = {};
      for (const key of Object.keys(item).sort()) {
        if (["__proto__", "prototype", "constructor"].includes(key)) continue;
        if (item[key] !== undefined)
          result[key] = normalize(item[key], depth + 1);
      }
      return result;
    };
    return JSON.stringify(normalize(value, 0));
  }

  private hash(value: unknown): string {
    return createHash("sha256")
      .update(this.stableStringify(value))
      .digest("hex");
  }

  private nullable(value?: string): string | null {
    return value?.trim() ? value.trim() : null;
  }

  private async audit(
    tx: any,
    actorId: string,
    action: string,
    entityType: string,
    entityId: string,
    before: Record<string, unknown> | null,
    after: Record<string, unknown> | null,
  ) {
    await tx.loyaltyWorkflowAudit.create({
      data: {
        actorId,
        action,
        entityType,
        entityId,
        ...(before ? { before } : {}),
        ...(after ? { after } : {}),
      },
    });
  }

  private prismaCode(error: unknown): string | undefined {
    return typeof error === "object" && error !== null && "code" in error
      ? String((error as { code?: unknown }).code)
      : undefined;
  }

  private notFound(): never {
    throw new NotFoundException("Запись не найдена");
  }

  private versionConflict(): never {
    throw new ConflictException(
      "Запись уже была изменена. Обновите данные и повторите действие",
    );
  }

  private stateConflict(): never {
    throw new ConflictException("Действие недоступно в текущем состоянии");
  }

  private selectionDrift(): never {
    throw new ConflictException(
      "Выбор записей изменился. Обновите список и повторите действие",
    );
  }

  private idempotencyConflict(): never {
    throw new ConflictException("Повторный запрос имеет другое содержимое");
  }
}
