/** Word program 1 Jan 2026 – 31 Jan 2027. Overlay / call book, not the «Сделки» column. */
export type ProgramPartnerKind = "АН" | "Ключевой" | "Частный";
export type ProgramPartnerList = "SOLD_2026" | "SLEEPING";

export interface ProgramPartner {
  key: string;
  name: string;
  kind: ProgramPartnerKind;
  list: ProgramPartnerList;
  dduCount: number;
  soldMln: number;
  priority: "A" | "B" | "C";
  rate: string | null;
  nextTier: string | null;
  lastDdu: string | null;
  offer: string | null;
  pitch: string;
}

export const PROGRAM_2026_SOURCE = {
  status: "UNCONFIRMED",
  accuracy: "UNKNOWN",
  periodApplied: false,
  provenance: "ANNA_LEGACY_WORD",
  documentName: "Лояльность_брокеров_исправленная_St_Michael.docx",
  declared: {
    soldPartners: 32,
    dduCount: 76,
    soldMln: 2367,
  },
  note: "Заголовок Word расходится с извлечёнными строками. Данные не пересчитаны по amoCRM и не входят в точные KPI.",
} as const;

export const PROGRAM_2026_PARTNERS: ProgramPartner[] = [
  {
    key: "ип-цюрупа-ю-а-highpoint",
    name: "ИП Цюрупа Ю.А. (HighPoint)",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 12,
    soldMln: 386.3,
    priority: "A",
    rate: "0,7%",
    nextTier: "+63,7 → 0,8%",
    lastDdu: null,
    offer: null,
    pitch: "386,3 млн ₽ / 12 ДДУ. Уровень 0,7%; до 0,8% — 63,7 млн ₽. Зафиксировать план.",
  },
  {
    key: "trend-agent",
    name: "Trend Agent",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 12,
    soldMln: 314.2,
    priority: "A",
    rate: "0,6%",
    nextTier: "+35,8 → 0,7%",
    lastDdu: null,
    offer: null,
    pitch: "314,2 млн ₽ / 12 ДДУ. Уровень 0,6%; до 0,7% — 35,8 млн ₽. Зафиксировать план.",
  },
  {
    key: "ип-пасхин",
    name: "ИП Пасхин",
    kind: "Ключевой",
    list: "SOLD_2026",
    dduCount: 3,
    soldMln: 196.6,
    priority: "A",
    rate: "0,5%",
    nextTier: "+103,4 → 0,6%",
    lastDdu: null,
    offer: null,
    pitch: "196,6 млн ₽. Сохраняем 0,5% до 31.01.2027; до 0,6% — 103,4 млн ₽. Подобрать лоты под цель.",
  },
  {
    key: "ип-журавлев",
    name: "ИП Журавлев",
    kind: "Ключевой",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 133.2,
    priority: "A",
    rate: "0,5%",
    nextTier: "+166,8 → 0,6%",
    lastDdu: null,
    offer: null,
    pitch: "133,2 млн ₽. Сохраняем 0,5% до 31.01.2027; до 0,6% — 166,8 млн ₽. Подобрать лоты под цель.",
  },
  {
    key: "flat",
    name: "Flat",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 5,
    soldMln: 124.1,
    priority: "B",
    rate: "0,2%",
    nextTier: "+25,9 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "124,1 млн ₽. До 0,3% — 25,9 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "неосити",
    name: "НЕОСИТИ",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 4,
    soldMln: 119.9,
    priority: "B",
    rate: "0,2%",
    nextTier: "+30,1 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "119,9 млн ₽. До 0,3% — 30,1 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "red-cat",
    name: "Red Cat",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 4,
    soldMln: 110.9,
    priority: "B",
    rate: "0,2%",
    nextTier: "+39,1 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "110,9 млн ₽. До 0,3% — 39,1 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ип-пешков",
    name: "ИП Пешков",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 2,
    soldMln: 88.1,
    priority: "C",
    rate: "0,2%",
    nextTier: "+61,9 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "88,1 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "этажи",
    name: "Этажи",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 3,
    soldMln: 76.8,
    priority: "C",
    rate: "0,2%",
    nextTier: "+73,2 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "76,8 млн ₽. До 0,3% — 73,2 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "гпр-агент",
    name: "ГПР Агент",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 2,
    soldMln: 76.5,
    priority: "C",
    rate: "0,2%",
    nextTier: "+73,5 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "76,5 млн ₽. До 0,3% — 73,5 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ип-хомякова",
    name: "ИП Хомякова",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 76.2,
    priority: "C",
    rate: "0,2%",
    nextTier: "+73,8 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "76,2 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "воробьева-эстейт",
    name: "Воробьева Эстейт",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 2,
    soldMln: 58.7,
    priority: "C",
    rate: "0,2%",
    nextTier: "+91,3 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "58,7 млн ₽. До 0,3% — 91,3 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "офис-на-петровке",
    name: "Офис на Петровке",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 2,
    soldMln: 53.0,
    priority: "C",
    rate: "0,2%",
    nextTier: "+97,0 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "53,0 млн ₽. До 0,3% — 97,0 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "прайм-самолет-плюс",
    name: "Прайм Самолет Плюс",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 3,
    soldMln: 52.4,
    priority: "C",
    rate: "0,2%",
    nextTier: "+97,6 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "52,4 млн ₽. До 0,3% — 97,6 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ооо-афк",
    name: "ООО «АФК»",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 2,
    soldMln: 42.9,
    priority: "C",
    rate: "0,2%",
    nextTier: "+107,1 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "42,9 млн ₽. До 0,3% — 107,1 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ип-семенова",
    name: "ИП Семенова",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 41.3,
    priority: "C",
    rate: "0,2%",
    nextTier: "+108,7 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "41,3 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "knokey",
    name: "Knokey",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 2,
    soldMln: 40.7,
    priority: "C",
    rate: "0,2%",
    nextTier: "+109,3 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "40,7 млн ₽. До 0,3% — 109,3 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ип-алигузева-ю-м",
    name: "ИП Алигузева Ю.М.",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 35.6,
    priority: "C",
    rate: "0,2%",
    nextTier: "+114,4 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "35,6 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "ип-атаулова",
    name: "ИП Атаулова",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 35.0,
    priority: "C",
    rate: "0,2%",
    nextTier: "+115,0 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "35,0 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "лайф-стрит",
    name: "Лайф Стрит",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 33.5,
    priority: "C",
    rate: "0,2%",
    nextTier: "+116,5 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "33,5 млн ₽. До 0,3% — 116,5 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "гордов",
    name: "Гордов",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 30.3,
    priority: "C",
    rate: "0,2%",
    nextTier: "+119,7 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "30,3 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "ип-арзуманов",
    name: "ИП Арзуманов",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 28.8,
    priority: "C",
    rate: "0,2%",
    nextTier: "+121,2 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "28,8 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "ип-кравченко",
    name: "ИП Кравченко",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 27.6,
    priority: "C",
    rate: "0,2%",
    nextTier: "+122,4 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "27,6 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "нмаркет",
    name: "Нмаркет",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 24.1,
    priority: "C",
    rate: "0,2%",
    nextTier: "+125,9 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "24,1 млн ₽. До 0,3% — 125,9 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "norman-group",
    name: "Norman Group",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 23.8,
    priority: "C",
    rate: "0,2%",
    nextTier: "+126,2 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "23,8 млн ₽. До 0,3% — 126,2 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ип-потапова",
    name: "ИП Потапова",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 21.4,
    priority: "C",
    rate: "0,2%",
    nextTier: "+128,6 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "21,4 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "мирная-ю-п",
    name: "Мирная Ю.П.",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 20.2,
    priority: "C",
    rate: "0,2%",
    nextTier: "+129,8 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "20,2 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "keygroup",
    name: "KeyGroup",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 20.1,
    priority: "C",
    rate: "0,2%",
    nextTier: "+129,9 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "20,1 млн ₽. До 0,3% — 129,9 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ип-савушкина",
    name: "ИП Савушкина",
    kind: "Частный",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 19.8,
    priority: "C",
    rate: "0,2%",
    nextTier: "+130,2 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "19,8 млн ₽. Личный звонок: три лота и дата следующего контакта.",
  },
  {
    key: "турголд",
    name: "Турголд",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 15.9,
    priority: "C",
    rate: "0,2%",
    nextTier: "+134,1 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "15,9 млн ₽. До 0,3% — 134,1 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ооо-мегаполис-сервис-эстейтлинг",
    name: "ООО «Мегаполис-сервис Эстейтлинг»",
    kind: "АН",
    list: "SOLD_2026",
    dduCount: 1,
    soldMln: 15.5,
    priority: "C",
    rate: "0,2%",
    nextTier: "+134,5 → 0,3%",
    lastDdu: null,
    offer: null,
    pitch: "15,5 млн ₽. До 0,3% — 134,5 млн ₽. Планёрка и подборка лотов.",
  },
  {
    key: "ofru",
    name: "OFRU",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 5,
    soldMln: 175.1,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "04.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 5 ДДУ на 175,1 млн ₽; последняя 04.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "союз-девелоперов-москвы-сдм",
    name: "Союз Девелоперов Москвы (СДМ)",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 4,
    soldMln: 159.8,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "10.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 4 ДДУ на 159,8 млн ₽; последняя 10.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-конеева",
    name: "ИП Конеева",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 129.5,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "18.02.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 129,5 млн ₽; последняя 18.02.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-тадевосян-а-в",
    name: "ИП Тадевосян А.В.",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 5,
    soldMln: 111.6,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "20.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 5 ДДУ на 111,6 млн ₽; последняя 20.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "10homes",
    name: "10Homes",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 3,
    soldMln: 92.8,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "24.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 3 ДДУ на 92,8 млн ₽; последняя 24.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "whitewill",
    name: "Whitewill",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 84.1,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "02.09.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 84,1 млн ₽; последняя 02.09.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "репрофит",
    name: "Репрофит",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 72.2,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "22.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 72,2 млн ₽; последняя 22.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "alvo-group",
    name: "ALVO Group",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 60.7,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "01.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 60,7 млн ₽; последняя 01.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-боганова",
    name: "ИП Боганова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 57.2,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "07.04.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 57,2 млн ₽; последняя 07.04.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "anwin-ип-андреев",
    name: "(Anwin) ИП Андреев",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 53.9,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "11.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 53,9 млн ₽; последняя 11.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "wellside",
    name: "Wellside",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 3,
    soldMln: 45.2,
    priority: "A",
    rate: null,
    nextTier: null,
    lastDdu: "08.07.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 3 ДДУ на 45,2 млн ₽; последняя 08.07.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "kalinka",
    name: "Kalinka",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 48.7,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "15.04.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 48,7 млн ₽; последняя 15.04.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "араника-эстейт",
    name: "Араника Эстейт",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 46.5,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "24.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 46,5 млн ₽; последняя 24.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-чурганова",
    name: "ИП Чурганова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 45.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "12.09.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 45,4 млн ₽; последняя 12.09.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ооо-единая-служба-недвижимости",
    name: "ООО Единая служба недвижимости",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 44.3,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "10.12.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 44,3 млн ₽; последняя 10.12.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "чудинова-о-ф",
    name: "Чудинова О.Ф.",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 42.3,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "15.05.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 42,3 млн ₽; последняя 15.05.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-тимофеев",
    name: "ИП Тимофеев",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 42.0,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "29.07.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 42,0 млн ₽; последняя 29.07.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "eniqma-group-ип-тимченко-и-и",
    name: "Eniqma Group(ИП Тимченко И.И.)",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 39.5,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "01.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 39,5 млн ₽; последняя 01.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ооо-тими",
    name: "ООО Тими",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 34.7,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "10.12.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 34,7 млн ₽; последняя 10.12.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "смарент",
    name: "Смарент",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 33.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "29.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 33,4 млн ₽; последняя 29.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "prime-sleeping",
    name: "PRIME",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 33.0,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "25.10.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 33,0 млн ₽; последняя 25.10.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-гурт-о-н",
    name: "ИП Гурт О.Н.",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 32.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "10.07.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 32,9 млн ₽; последняя 10.07.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-михайлова",
    name: "ИП Михайлова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 31.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "10.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 31,4 млн ₽; последняя 10.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "арт-риэлти",
    name: "Арт риэлти",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 30.8,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "24.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 30,8 млн ₽; последняя 24.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-шабанова",
    name: "ИП Шабанова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 2,
    soldMln: 30.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "08.08.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 2 ДДУ на 30,4 млн ₽; последняя 08.08.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-озолина",
    name: "ИП Озолина",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 30.1,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "11.07.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 30,1 млн ₽; последняя 11.07.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "simplicity",
    name: "SimpliCity",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 29.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "02.09.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 29,9 млн ₽; последняя 02.09.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-чебаров",
    name: "ИП Чебаров",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 29.8,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "21.08.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 29,8 млн ₽; последняя 21.08.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "barnes",
    name: "Barnes",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 29.1,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "22.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 29,1 млн ₽; последняя 22.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-байбекова",
    name: "ИП Байбекова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 28.7,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "19.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 28,7 млн ₽; последняя 19.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-ковальчук",
    name: "ИП Ковальчук",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 27.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "20.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 27,9 млн ₽; последняя 20.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-хорьякова",
    name: "ИП Хорьякова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 27.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "27.02.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 27,4 млн ₽; последняя 27.02.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "сз-девятовская",
    name: "СЗ Девятовская",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 27.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "04.04.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 27,4 млн ₽; последняя 04.04.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-айрапетян",
    name: "ИП Айрапетян",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 26.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "29.09.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 26,9 млн ₽; последняя 29.09.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-волков-я-в",
    name: "ИП Волков Я.В",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 26.4,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "29.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 26,4 млн ₽; последняя 29.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-попов",
    name: "ИП Попов",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 23.2,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "02.10.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 23,2 млн ₽; последняя 02.10.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-ефимова",
    name: "ИП Ефимова",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 22.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "22.07.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 22,9 млн ₽; последняя 22.07.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ооо-союз-эксперт",
    name: "ООО Союз-Эксперт",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 21.2,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "12.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 21,2 млн ₽; последняя 12.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ооо-практик",
    name: "ООО Практик",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 21.1,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "15.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 21,1 млн ₽; последняя 15.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "prime-sleeping",
    name: "Prime",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 18.3,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "26.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 18,3 млн ₽; последняя 26.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "дом-в-столице-ип-песоцкая-т-м",
    name: "«Дом в Столице» ИП Песоцкая Т.М",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "08.08.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,9 млн ₽; последняя 08.08.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "мегаполис",
    name: "Мегаполис",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.8,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "11.12.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,8 млн ₽; последняя 11.12.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-соболева",
    name: "ИП Соболева",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.5,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "06.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,5 млн ₽; последняя 06.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "braumost-ип-цирени",
    name: "Braumost(ИП Цирени)",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.3,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "16.09.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,3 млн ₽; последняя 16.09.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-саяпин",
    name: "ИП Саяпин",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 16.2,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "12.09.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 16,2 млн ₽; последняя 12.09.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "домгоу",
    name: "Домгоу",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 15.9,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "06.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 15,9 млн ₽; последняя 06.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "биг-сити-ип-жакова",
    name: "Биг Сити (ИП Жакова)",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 15.1,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "19.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 15,1 млн ₽; последняя 19.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-зайтцев",
    name: "ИП Зайтцев",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 14.5,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "19.11.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 14,5 млн ₽; последняя 19.11.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-еремина",
    name: "ИП Еремина",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 13.6,
    priority: "B",
    rate: null,
    nextTier: null,
    lastDdu: "31.07.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 13,6 млн ₽; последняя 31.07.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "обьединение-застройщиков",
    name: "Обьединение застройщиков",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 24.7,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "06.06.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 24,7 млн ₽; последняя 06.06.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "смз-васильев",
    name: "СМЗ Васильев",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 24.2,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "26.06.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 24,2 млн ₽; последняя 26.06.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-схинас",
    name: "ИП Схинас",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 23.8,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "13.03.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 23,8 млн ₽; последняя 13.03.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "спн24",
    name: "СПН24",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 19.5,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "17.05.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 19,5 млн ₽; последняя 17.05.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "open-city",
    name: "Open City",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.5,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "20.03.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,5 млн ₽; последняя 20.03.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  },
  {
    key: "ип-познянская",
    name: "ИП Познянская",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.3,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "11.04.2024",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,3 млн ₽; последняя 11.04.2024. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "ип-осадчая-ип-широченкова-д-ф",
    name: "ИП Осадчая(ИП Широченкова Д.Ф)",
    kind: "Частный",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 17.3,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "17.02.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 17,3 млн ₽; последняя 17.02.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; отправить личную подборку из 3 лотов.",
  },
  {
    key: "сз-филатова",
    name: "СЗ Филатова",
    kind: "АН",
    list: "SLEEPING",
    dduCount: 1,
    soldMln: 14.6,
    priority: "C",
    rate: null,
    nextTier: null,
    lastDdu: "20.06.2025",
    offer: "+0,5% на 1-й ДДУ · до 30.09.2026",
    pitch: "Ранее: 1 ДДУ на 14,6 млн ₽; последняя 20.06.2025. Предложить +0,5% на первую новую сделку до 30.09.2026; провести планёрку и показать 5 подходящих лотов.",
  }
];
